#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt extendedglob
setopt nobraceccl

export PATH="/usr/local/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin:/usr/bin:$HOME/bin"

# For tramp happiness
if [[ "$TERM" == "dumb" ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  # No longer needed with zprezto?
  #unfunction precmd
  #unfunction preexec
  PS1='$ '
  return
fi

for fl in $HOME/.zprezto/runcoms/custom/*.zsh; do
  . $fl
done

if [[ "$(uname -s)" = "OpenBSD" ]]; then
    FQDN=$(hostname)
else
    FQDN=$(hostname -f)
fi

export FQDN

if [ -r ~/.zprezto/runcoms/byhost/$FQDN ]; then
    . ~/.zprezto/runcoms/byhost/$FQDN
fi

# Set up the completion directory
fpath+="$HOME/.zprezto/completion"
compinit

# If starship is available, initialize
if which starship >& /dev/null; then
   eval "$(starship init zsh)"
fi
