#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

CUSTOM_COMPLETION_DIR="${ZDOTDIR:-$HOME}/.zprezto/completion"
if [[ -d "${CUSTOM_COMPLETION_DIR}" ]]; then
   fpath+="${CUSTOM_COMPLETION_DIR}"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt extendedglob
setopt nobraceccl

export PATH="/usr/local/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin:/usr/bin:$HOME/bin"

# For tramp happiness
if [[ "$TERM" == "dumb" ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  # No longer needed with zprezto?
  #unfunction precmd
  #unfunction preexec
  PS1='$ '
  return
fi

for fl in $HOME/.zprezto/runcoms/custom/*.zsh; do
  . $fl
done

if [ -r ~/.zprezto/runcoms/byhost/$(hostname -f) ]; then
    . ~/.zprezto/runcoms/byhost/$(hostname -f)
fi

# Try out starship
eval "$(starship init zsh)"

# Run compinit (again?!?!) to get custom completions
compinit

# # Enable fzf completion
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# [ -f ~/Tools/fzf-tab-completion/zsh/fzf-zsh-completion.sh ] && source ~/Tools/fzf-tab-completion/zsh/fzf-zsh-completion.sh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/ssdhome/derek/.sdkman"
[[ -s "/ssdhome/derek/.sdkman/bin/sdkman-init.sh" ]] && source "/ssdhome/derek/.sdkman/bin/sdkman-init.sh"
