bind b send-prefix
bind C-b last-window

set -g mode-keys emacs
setw -g aggressive-resize on
set-window-option -g xterm-keys on

set -s escape-time 75

# Use emacs-style alt-arrows for word movement
bind-key -T copy-mode M-Left send-keys -X previous-word
bind-key -T copy-mode M-Right send-keys -X next-word-end

# Set the window title based on whatever things are
set -g set-titles on
set -g set-titles-string "#(hostname)"

# Make the "right" status more useful
set -g status-right "#S/#(hostname)"

# Fix 24-bit color in emacs (https://github.com/troyp/spacemacs/wiki/Terminal)
# Adapted for tmux keymap (e.g. Home/End)
set -g default-terminal "xterm-24bit"
set -g terminal-overrides ',xterm-24bit:Tc'
# And to fix some escapes... (https://stackoverflow.com/a/55616731)
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# # An attempt to adapt for tmux keymap (e.g. Home/End)
# set -g default-terminal "tmux-24bit"
# set -g terminal-overrides ',tmux-24bit:Tc'
